project:
  type: website
  output-dir: docs/
website:
  announcement: 
    icon: info-circle
    dismissable: true
    content: "Definition: 1) Pass: All gains within 100% baseline and all RCVs <6% for all detectors 2) Caution: All Gains passed, but at least one detector had a RCV above the >6% cutoff. Instrument remains usable but decreased resolution for fluorophores on that detector is possible. 3) Fail: A gain exceeded 100% baseline, or RCVs exceeded >6% for at least the indicator detectors. Significant batch effects may occcur"
    type: primary
    position: above-navbar  
  title: "UMGCC FCSS"
  site-path: "/InstrumentQC/"
  navbar:
    logo: images/hex.svg
    left:
    - text: "Home"
      href: index.qmd
    - text: "3L"
      href: Aurora3L.qmd
    - text: "4L"
      href: Aurora4L.qmd
    - text: "5L"
      href: Aurora5L.qmd
    - text: "CS"
      href: AuroraCS.qmd
    - text: "Canto"
      href: CantoII.qmd
    - text: "LSR"
      href: LSRII.qmd
    - text: "Aria"
      href: AriaII.qmd
    right:
    - text: "Data"
      href: Data.qmd
    - text: "Help"
      href: help.qmd
    - text: "Other"
      menu:
      - text: "Miscellaneous"
        href: Miscellaneous.qmd 
      - text: "QC Bead Lots"
        href: CytekQCBead.qmd
    - icon: github
      href: https://github.com/UMGCCFCSS/InstrumentQC
      aria-label: GitHub
  page-footer:
    background: light
    left: University of Maryland, Baltimore
    right: Built with [Quarto](https://quarto.org/){target=_blank}

format:
  html:
    theme: styles.scss