project:
  type: website
  output-dir: docs/

website: 
  title: "UMGCC FCSS"
  navbar:
    logo: images/hex.svg
    left:
    - text: "Home"
      href: home.qmd
    - text: "3L"
      href: Aurora3L.qmd
    - text: "4L"
      href: Aurora4L.qmd
    - text: "5L"
      href: Aurora5L.qmd
    - text: "CS"
      href: AuroraCS.qmd

format:
  html:
    theme: simplex