---
format:
  dashboard:
    orientation: rows
project:
  output-dir: docs/
---

```{r}
library(htmltools)
```

## First Row

### 3L

```{r}
#| content: valuebox
#| title: "3L"
#| icon: cup-hot

HTML("
<ul>
  <li><a href='data/3L/Archive/ArchivedData3L.csv'>Gain and %rCV</a></li>
  <li><a href='data/3L/Archive/BeadData3L.csv'>MFI</a></li>
  <li><a href='data/QCPlots_3L.pdf'>Plots</a></li>
</ul>
")
```

### 4L

```{r}
#| content: valuebox
#| title: "4L"
#| icon: cup-hot

HTML("
<ul>
  <li><a href='data/4L/Archive/ArchivedData4L.csv'>Gain and %rCV</a></li>
  <li><a href='data/4L/Archive/BeadData4L.csv'>MFI</a></li>
  <li><a href='data/QCPlots_4L.pdf'>Plots</a></li>
</ul>
")
```

## Second Row

### 5L

```{r}
#| content: valuebox
#| title: "5L"
#| icon: cup-hot

HTML("
<ul>
  <li><a href='data/5L/Archive/ArchivedData5L.csv'>Gain and %rCV</a></li>
  <li><a href='data/5L/Archive/BeadData5L.csv'>MFI</a></li>
  <li><a href='data/QCPlots_5L.pdf'>Plots</a></li>
</ul>
")
```

### CS

```{r}
#| content: valuebox
#| title: "CS"
#| icon: cup-hot

HTML("
<ul>
  <li><a href='data/CS/Archive/ArchivedDataCS.csv'>Gain and %rCV</a></li>
  <li><a href='data/CS/Archive/BeadDataCS.csv'>MFI</a></li>
  <li><a href='data/QCPlots_CS.pdf'>Plots</a></li>
</ul>
")
```