Please save the below as .R files for each individual computer. This FlagRemoval.R file is then called by source(FlagRemoval.R) in the TaskSchedule process to remove any generated Flag.csv files at the end of the day, resetting the automatic processing for the next day. 

```{r}
#| eval: false

# 3L
Main <- file.path("C:", "DailyQC", "InstrumentQC")
AnyFlags <- list.files(Main, pattern="Flag.csv", full.names=TRUE)

if (!length(AnyFlags) == 0){
  TheCSV <- file.path(Main, "Flag.csv")
  file.remove(TheCSV)
}
```

```{r}
#| eval: false

# 4L
Main <- file.path("C:", "DailyQC", "InstrumentQC")
AnyFlags <- list.files(Main, pattern="Flag.csv", full.names=TRUE)

if (!length(AnyFlags) == 0){
  TheCSV <- file.path(Main, "Flag.csv")
  file.remove(TheCSV)
}
```

```{r}
#| eval: false

# 5L
Main <- file.path("C:", "Users", "Aurora", "Documents", "InstrumentQC")
AnyFlags <- list.files(Main, pattern="Flag.csv", full.names=TRUE)

if (!length(AnyFlags) == 0){
  TheCSV <- file.path(Main, "Flag.csv")
  file.remove(TheCSV)
}
```

```{r}
#| eval: false

# CS
Main <- file.path("C:", "Users", "Aurora CS", "Documents", "InstrumentQC")
AnyFlags <- list.files(Main, pattern="Flag.csv", full.names=TRUE)

if (!length(AnyFlags) == 0){
  TheCSV <- file.path(Main, "Flag.csv")
  file.remove(TheCSV)
}
```


