---
toc: true
---

# Types of Measurements

## Gain
Gain (similar to voltage on certain cytometers) is a unit by which the detected signal is amplified by for each detector. During the Daily QC, gains are adjusted in order to ensure that the MFI of the instrument is maintained to allow for comparison across experiment days. When a laser starts to wear out, the amount of gain needed to keep the MFI stable will increase. 

When a gain for any individual detector is twice that of it's original baseline gain value, it will be marked as having failed during the Daily QC.  

## %rCV

When the robust coefficient of variation (rCV) is low, it's possible to reproducible discern dim staining populations from each other. When the variance is higher, this ability to discern can be lost. 

Cytek defines a detector having failed QC when it's %rCV fail exceeds 6% for the FSC, UV3, V3, B3, YG3, R3 detectors, or 8% for the SSC detectors. When any of the above occurs, it will be marked as having failed Daily QC.

What about in the case of the other detectors (UV1-UV16, etc.)? While they don't trigger a Daily QC fail, they can still impact an experiment. In the context of our dashboard, if a greater than 6% rCV is observed for any of these other detectors, they will be marked by the yellow caution/warning designations.

## MFI

The Mean Fluorescent Intensity (MFI) is based on the measured brightness values across individual detectors for the QC beads acquired during daily QC. Based on these initial MFI results, during Daily QC to Gain is adjusted to ensure that the MFI is stable across time. We can visualize this process by comparing the measurements taken from the before/after QC bead samples. 

While Daily QC doesn't fail due to a change of MFI, we can observe potential issues by checking to see whether the MFI for a given detector is maintained over time, or if it swings wildly over time. This often times coincides with observed QC failure for both the Gain and %rCV measurements. 

# Interactive Plots

The interactive plots are laid out in three columns (MFI, Gain, %rCV), with each tab showing the individual laser detectors in order. Additional parameters (Scatter, LaserPower, LaserDelay, LaserAreaScaling) appear as individual tabs when they are recorded by the individual instruments. 

When a QC fail occurs for a given parameter, it appears as a red box on that individual date and when hovered over the flag will appear as TRUE. 

When the data is available, the plots will show the instrumental data for the given parameter as recorded by the daily QC's from the last year. You can select the options on the upper right of the plot to zoom in and out of a particular region of interest, and to save an individual plot as a .png to your own computer. 

# Data

All data used to derive the dashboard interactive plots for the individual instruments is available to download under the Data tab on the upper right of the page. 

Gain and % rCV links to the current data derived from the Daily QC reports in the form of a .csv. It can be used if you want to plot the data yourself and use a better ggplot2 color-scheme in R.  

MFI is the current data derived from the Before and After QC Bead .fcs files processed to return the MFI and Gain values for the individual files. It is also available as a .csv file. 

Plots is a .pdf containing static versions of all the interactive plots for the individual instrument (MFI, Gain, %rCV). In addition to QC fails being flagged by red squares, it contains vertical red dashed lines corresponding to dates when the engineer was here for repairs or preventative maintenance. 
