```{r}
#| eval: FALSE
#| warning: false
#| message: false

library(utils)
library(taskscheduleR)
```
# Test

```{r}
#| eval: false

taskscheduler_delete("QC_5L_Test")
taskscheduler_ls()
?taskscheduler_create
```



# 3L
```{r}
#| eval: FALSE
#taskscheduler_delete("RepoPull")

# Automated QC
WorkingDirectory <- file.path("C:", "DailyQC", "InstrumentQC")
TheScript <- file.path(WorkingDirectory, "TheScript_3L.R")

taskscheduler_create(taskname = "QC_3L_Morning",
                     rscript=TheScript,
                     schedule="DAILY",
                     startdate = format(Sys.Date(), "%m/%d/%Y"),
                     starttime = "10:30",
                     schtasks_extra = '/RU SYSTEM')

# Automated QC
WorkingDirectory <- file.path("C:", "DailyQC", "InstrumentQC")
TheScript <- file.path(WorkingDirectory, "TheScript_3L.R")

taskscheduler_create(taskname = "QC_3L_Morning_2",
                     rscript=TheScript,
                     schedule="DAILY",
                     startdate = format(Sys.Date(), "%m/%d/%Y"),
                     starttime = "22:00",
                     schtasks_extra = '/RU SYSTEM')

# Flag Removal
WorkingDirectory <- file.path("C:", "DailyQC", "InstrumentQC")
TheFlagScript <- file.path(WorkingDirectory, "FlagRemoval.R")

taskscheduler_create(taskname = "FlagRemoval",
                     rscript=TheFlagScript,
                     schedule="DAILY",
                     startdate = format(Sys.Date(), "%m/%d/%Y"),
                     starttime = "13:00",
                     schtasks_extra = '/RU SYSTEM')

# Repo Pull
WorkingDirectory <- file.path("C:", "DailyQC", "InstrumentQC")
TheRepoPull <- file.path(WorkingDirectory, "RepoPull.R")

taskscheduler_create(taskname = "RepoPull",
                     rscript=TheRepoPull,
                     schedule="DAILY",
                     startdate = format(Sys.Date(), "%m/%d/%Y"),
                     starttime = "06:00",
                     schtasks_extra = '/RU SYSTEM')

#source("C:/Users/12692/Documents/ILT_Analysis/TestScheduler1.R")
#taskscheduler_ls()
#taskscheduler_delete("QC_3L_Morning")
```


# 4L
```{r}
#| eval: FALSE
#taskscheduler_delete("RepoPull")

# Automated QC
WorkingDirectory <- file.path("C:", "DailyQC", "InstrumentQC")
TheScript <- file.path(WorkingDirectory, "TheScript_4L.R")

taskscheduler_create(taskname = "QC_4L_Morning",
                     rscript=TheScript,
                     schedule="DAILY",
                     startdate = format(Sys.Date(), "%m/%d/%Y"),
                     starttime = "10:32",
                     schtasks_extra = '/RU SYSTEM')

# Automated QC
WorkingDirectory <- file.path("C:", "DailyQC", "InstrumentQC")
TheScript <- file.path(WorkingDirectory, "TheScript_4L.R")

taskscheduler_create(taskname = "QC_4L_Morning_2",
                     rscript=TheScript,
                     schedule="DAILY",
                     startdate = format(Sys.Date(), "%m/%d/%Y"),
                     starttime = "22:00",
                     schtasks_extra = '/RU SYSTEM')

# Flag Removal
WorkingDirectory <- file.path("C:", "DailyQC", "InstrumentQC")
TheFlagScript <- file.path(WorkingDirectory, "FlagRemoval.R")

taskscheduler_create(taskname = "FlagRemoval",
                     rscript=TheFlagScript,
                     schedule="DAILY",
                     startdate = format(Sys.Date(), "%m/%d/%Y"),
                     starttime = "13:00",
                     schtasks_extra = '/RU SYSTEM')

# Repo Pull
WorkingDirectory <- file.path("C:", "DailyQC", "InstrumentQC")
TheRepoPull <- file.path(WorkingDirectory, "RepoPull.R")

taskscheduler_create(taskname = "RepoPull",
                     rscript=TheRepoPull,
                     schedule="DAILY",
                     startdate = format(Sys.Date(), "%m/%d/%Y"),
                     starttime = "06:00",
                     schtasks_extra = '/RU SYSTEM')

#source("C:/Users/12692/Documents/ILT_Analysis/TestScheduler1.R")
#taskscheduler_ls()
#taskscheduler_delete("QC_4L_Morning")
```


# 5L
```{r}
#| eval: FALSE
WorkingDirectory <- file.path("C:", "Users", "Aurora", "Documents", "InstrumentQC")
TheScript <- file.path(WorkingDirectory, "TheScript_5L.R")
taskscheduler_create(taskname = "QC_5L_Morning",
                     rscript=TheScript,
                     schedule="DAILY",
                     startdate = format(Sys.Date(), "%m/%d/%Y"),
                     starttime = "10:34")


# Automated QC
WorkingDirectory <- file.path("C:", "Users", "Aurora", "Documents", "InstrumentQC")
TheScript <- file.path(WorkingDirectory, "TheScript_5L.R")
taskscheduler_create(taskname = "QC_5L_Morning_2",
                     rscript=TheScript,
                     schedule="DAILY",
                     startdate = format(Sys.Date(), "%m/%d/%Y"),
                     starttime = "22:11")
#schtasks_extra = '/RU SYSTEM'

# Flag Removal
WorkingDirectory <- file.path("C:", "Users", "Aurora", "Documents", "InstrumentQC")
TheFlagScript <- file.path(WorkingDirectory, "FlagRemoval.R")
taskscheduler_create(taskname = "FlagRemoval",
                     rscript=TheFlagScript,
                     schedule="DAILY",
                     startdate = format(Sys.Date(), "%m/%d/%Y"),
                     starttime = "13:00")

#Repo Pull
WorkingDirectory <- file.path("C:", "Users", "Aurora", "Documents", "InstrumentQC")
TheRepoPull <- file.path(WorkingDirectory, "RepoPull.R")
#source(TheRepoPull)

taskscheduler_create(taskname = "RepoPull",
                     rscript=TheRepoPull,
                     schedule="DAILY",
                     startdate = format(Sys.Date(), "%m/%d/%Y"),
                     starttime = "06:00")

#source("C:/Users/12692/Documents/ILT_Analysis/TestScheduler1.R")
#taskscheduler_ls()
#taskscheduler_delete("QC_5L_Morning")
```

# CS
```{r}
#| eval: FALSE
# Automated QC
Main <- file.path("C:", "Users", "Aurora CS")
RepositoryPath <- file.path(Main, "Documents", "InstrumentQC", "TheScript_CS.R")
taskscheduler_create(taskname = "QC_CS_Morning",
                     rscript=RepositoryPath,
                     schedule="DAILY",
                     startdate = format(Sys.Date(), "%m/%d/%Y"),
                     starttime = "10:36")

# Automated QC
Main <- file.path("C:", "Users", "Aurora CS")
RepositoryPath <- file.path(Main, "Documents", "InstrumentQC", "TheScript_CS.R")
taskscheduler_create(taskname = "QC_CS_Morning_2",
                     rscript=RepositoryPath,
                     schedule="DAILY",
                     startdate = format(Sys.Date(), "%m/%d/%Y"),
                     starttime = "22:15")

# Flag Removal
Main <- file.path("C:", "Users", "Aurora CS", "Documents", "InstrumentQC")
TheFlagScript <- file.path(Main, "FlagRemoval.R")
taskscheduler_create(taskname = "FlagRemoval",
                     rscript=TheFlagScript,
                     schedule="DAILY",
                     startdate = format(Sys.Date(), "%m/%d/%Y"),
                     starttime = "13:00")

#Repo Pull
WorkingDirectory <- file.path("C:", "Users", "Aurora CS", "Documents", "InstrumentQC")
TheRepoPull <- file.path(WorkingDirectory, "RepoPull.R")
taskscheduler_create(taskname = "RepoPull",
                     rscript=TheRepoPull,
                     schedule="DAILY",
                     startdate = format(Sys.Date(), "%m/%d/%Y"),
                     starttime = "06:00")

#source(TheFlagScript)
#taskscheduler_ls()
#taskscheduler_delete("QC_CS_Morning")
```
