---
format:
  dashboard:
    orientation: rows
project:
  output-dir: docs/
---

```{r}
library(htmltools)
```

## {.sidebar}

This dashboard contains the visualized QC data for the Cytek Auroras at the [UMGCC FCSS](https://www.medschool.umaryland.edu/cibr/core/umgccc_flow/)

For additional flow cytometry resources, visit our [website](https://sites.google.com/view/umgcccflow/home)

This dashboard was created with [Quarto](https://quarto.org/) and is maintained by [David Rach](https://github.com/DavidRach)


## First Row {height="50%"}

### 3L {width="50%"}

::: {.card title="" width="33%"}

:::

```{r}
#| content: valuebox
#| title: "3L"
#| icon: cup-hot

HTML("
<ul>
  <li><a href='data/3L/Archive/ArchivedData3L.csv'>Gain and %rCV</a></li>
  <li><a href='data/3L/Archive/BeadData3L.csv'>MFI</a></li>
  <li><a href='data/QCPlots_3L.pdf'>Plots</a></li>
</ul>
")
```

### 5L {width="50%"}

::: {.card title="" width="33%"}

:::

```{r}
#| content: valuebox
#| title: "5L"
#| icon: cup-hot

HTML("
<ul>
  <li><a href='data/5L/Archive/ArchivedData5L.csv'>Gain and %rCV</a></li>
  <li><a href='data/5L/Archive/BeadData5L.csv'>MFI</a></li>
  <li><a href='data/QCPlots_5L.pdf'>Plots</a></li>
</ul>
")
```




## Second Row {height="50%"}

### 4L {width="50%"}

```{r}
#| content: valuebox
#| title: "4L"
#| icon: cup-hot

HTML("
<ul>
  <li><a href='data/4L/Archive/ArchivedData4L.csv'>Gain and %rCV</a></li>
  <li><a href='data/4L/Archive/BeadData4L.csv'>MFI</a></li>
  <li><a href='data/QCPlots_4L.pdf'>Plots</a></li>
</ul>
")
```

::: {.card title="" width="33%"}

:::

### CS {width="50%"}

```{r}
#| content: valuebox
#| title: "CS"
#| icon: cup-hot

HTML("
<ul>
  <li><a href='data/CS/Archive/ArchivedDataCS.csv'>Gain and %rCV</a></li>
  <li><a href='data/CS/Archive/BeadDataCS.csv'>MFI</a></li>
  <li><a href='data/QCPlots_CS.pdf'>Plots</a></li>
</ul>
")
```

::: {.card title="" width="33%"}

:::

 